### ISSUE TITLE
Migration to a PSR-15 Middleware for Flow 8 compatibility

### ISSUE THREAD

**Issue by auwaerter** [flownative/flow-prometheus-flow-metrics#2]
I've tried to replace the component chain with a PSR-15 middleware, so it is compatible with Flow 8. 

For this, i've touched the original [HttpMetricsCollectorComponent.php](https://github.com/flownative/flow-prometheus-flow-metrics/blob/master/Classes/HttpMetricsCollectorComponent.php) and modified it the [following way](https://gist.github.com/auwaerter/33ef5b44161c8d522a71ac88835229d9). In addition, i've changed the original [Settings.Http.yaml](https://github.com/flownative/flow-prometheus-flow-metrics/blob/master/Configuration/Settings.Http.yaml) to the [following](https://gist.github.com/auwaerter/a0dec7df7f5cbd8a97c4ffa3322806f8), to register it as a middleware.

I've understood, that for this package to run i need to have [flownative/prometheus v1.2.0](https://github.com/flownative/flow-prometheus) installed and configured. That's what i did with some global configuration for my Neos project:

```yaml
Flownative\Prometheus\DefaultCollectorRegistry:
  arguments:
    1:
      object: Flownative\Prometheus\Storage\RedisStorage

Flownative\Prometheus\Storage\RedisStorage:
  arguments:
    1:
      value:
        hostname: 'redis-service'
        port: '6379'
        password: 'xxxx'
        database: 8
        ignoreConnectionErrors: false

Flownative\Prometheus\Http\MetricsExporterMiddleware:
  arguments:
    1:
      value:
        ## Path at which metrics are published for scraping
        telemetryPath: '/metrics'
```
However, beside receiving the message `# Flownative Prometheus Metrics Exporter: There are currently no metrics with data to export.` when i'm opening `https://host/metrics` also the redis database seems to be empty:

```bash
redis-cli
auth XXX
SELECT 8
127.0.0.1:6379[8]> KEYS *
(empty array)
127.0.0.1:6379[8]>
```

This package does not seem to be touched for quite some time, so i'm wondering if it is still maintained - or if i should move to something else instead. Could there be any configuration issue on my side?

Any help is appreciated! :)
